package com.dassiorleando.apachecayenne.models.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AutoPkSupport was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AutoPkSupport extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String TABLE_NAME_PK_COLUMN = "TABLE_NAME";

    public static final Property<Long> NEXT_ID = Property.create("nextId", Long.class);

    public void setNextId(long nextId) {
        writeProperty("nextId", nextId);
    }
    public long getNextId() {
        Object value = readProperty("nextId");
        return (value != null) ? (Long) value : 0;
    }

}
